### PR TITLE
Allow to change bar anchor points

### PR DESCRIPTION
**Pull request by pshurgal**
I usually play in windowed mode and change size of the window sometimes. But after each resize I had to open the setting menu and change positions of castbars.
Now I can anchor castbars to different sides of the window (center usually). And after window resizing castbars stay ot heir positions and look well.

### CODE REVIEW

**Review by DigitalDJ — APPROVED** [review]

**Comment by pshurgal** [comment]
@Nevcairiel how about merge?

**Comment by gaffneyc** [comment]
@Nevcairiel Any chance of getting this merged? I run into this quite a bit switching between laptop screen and an external monitor.

**Comment by Nevcairiel** [comment]
I actually went with a different approach using LibWindow instead of manually handling all the logic, which is what I do in my other addons already. But the end-result should be the same, proper position relative to the screen edge.

**Comment by pshurgal** [comment]
@Nevcairiel any chance of getting this in classic branch? As I can see it hasn't been updated for a year.

**Pull request closed without merging**
